version: '3'
services:

  #PHP Service
  app:
    # container_name: app
    build:
      context: $DOCKER_CONFIG_PATH/
      dockerfile: Dockerfile
    image: tiagofranca.com/php74-pg
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      COMPOSER_CACHE_DIR: /home/www/COMPOSER_CACHE_DIR
    working_dir: /var/www
    volumes:
      - $PROJECT_DIR:/var/www
      - $DOCKER_CONFIG_PATH/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /tmp:/tmp/tmp_host/
      ## Executar:  touch ./_dev_dir/{psysh_history,bash_history.txt}
      - ./_dev_dir/psysh_history:/home/www/.config/psysh/psysh_history
      - ./_dev_dir/bash_history.txt:/home/www/.bash_history
      - ~/.ssh:/home/www/.ssh
      - ~/.bash_aliases:/home/www/.bash_aliases
      - ${COMPOSER_CACHE_DIR:-./env_COMPOSER_CACHE_DIR}:/home/www/COMPOSER_CACHE_DIR
    networks:
      - app-network

  #NGINX Service
  webserver:
    # container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT:-8000}:80"
    volumes:
      - "$PROJECT_DIR:/var/www"
      - "$DOCKER_CONFIG_PATH/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
