version: '3'
services:

## Parcialmente (a parte de jobs e script em loop) baseado no tutorial https://laravel-news.com/laravel-scheduler-queue-docker
## Modificado para usar o php-fpm e ngnix
## O ideal seria utilizar o supervisor

################################################
### Service - app [desc: Executa o php-fpm e entrega a porta 9000 para o webserver]
  app:
    build:
      context: .
      dockerfile: ./docker-php7.4_laravel-loop-work/Dockerfile
    image: tiagofranca/php74-loop-work
#    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-php7.4_laravel-loop-work/start.sh:/usr/local/bin/start
      - ./docker-php7.4_laravel-loop-work/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

################################################
### Service - scheduler [desc: executa 'artisan schedule:run' que roda os schedules do Laravel]
#  scheduler:
#    image: tiagofranca/php74-loop-work
##    container_name: scheduler
#    restart: unless-stopped
#    tty: true
#    environment:
#      APP_ENV: local
#      CONTAINER_ROLE: scheduler
#      SERVICE_NAME: scheduler
#      SERVICE_TAGS: dev
#    working_dir: /var/www
#    volumes:
#      - ./:/var/www
#      - ./docker-php7.4_laravel-loop-work/start.sh:/usr/local/bin/start
#      - ./docker-php7.4_laravel-loop-work/php/local.ini:/usr/local/etc/php/conf.d/local.ini
#    networks:
#      - app-network

################################################
### Service - queue [desc: executa 'artisan queue:work' que executa os jobs do Laravel ]
  queue:
    image: tiagofranca/php74-loop-work
#    container_name: queue
    restart: unless-stopped
    tty: true
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      SERVICE_NAME: queue
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-php7.4_laravel-loop-work/start.sh
      - ./docker-php7.4_laravel-loop-work/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
#    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
#      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-php7.4_laravel-loop-work/start.sh:/usr/local/bin/start
      - ./docker-php7.4_laravel-loop-work/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
