version: '2'
services:
  #######################################
  # PHP application Docker container
  # Passwords in webdevops_docker/documentation/SERVICES.md
  # Default user, pass: root/dev dev
  #######################################
  app:
    build:
      context: ./webdevops_docker
      dockerfile: Dockerfile.development
    links:
      # - postgresgis
      # - mail
    #  - mysql
      #- postgres
      #- solr
      #- elasticsearch
      - redis
      #- memcached
      #- ftp
    ports:
      - "8000:80"
      # - "3000:80"
      # - "8001:80"
      # - "8002:8000"
      # - "8080:8080"
      # - "8081:8081"
      # - "10443:443"
      - "10022:22"
    working_dir: /app
    volumes:
      - /:/host_root
      - ./:/app/
      - ./_dev_dir/bash_alises.sh:/root/.bash_aliases
      - ./webdevops_docker/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      - ./webdevops_docker/:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - ./webdevops_docker/etc/environment.yml
      - ./webdevops_docker/etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025

  #omnidb:
  #  image: taivokasper/omnidb
  #  volumes:
  #    - config-omnidb:/etc/omnidb
  #  links:
  #    # - postgresgis:postgres
  #    - mysql:mysql
  #  ports:
  #    - "8090:8080"
  #    - "25482:25482"

  #######################################
  # MySQL server
  #######################################
  #mysql:
  #  build:
  #    context: ./webdevops_docker/docker/mysql/
  #    #dockerfile: MySQL-5.5.Dockerfile
  #    dockerfile: MySQL-5.6.Dockerfile
  #    #dockerfile: MySQL-5.7.Dockerfile
  #    #dockerfile: MariaDB-5.5.Dockerfile
  #    #dockerfile: MariaDB-10.Dockerfile
  #    #dockerfile: Percona-5.5.Dockerfile
  #    #dockerfile: Percona-5.6.Dockerfile
  #    #dockerfile: Percona-5.7.Dockerfile
  #  ports:
  #    - 13306:3306
  #  volumes:
  #    - mysql:/var/lib/mysql
  #  env_file:
  #    # - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml

  #######################################
  # PostgreSQL server com POSTGIS
  #######################################
  # postgresgis:
  ##  build:
  ##    context: ./webdevops_docker/docker/postgres/
  ##    dockerfile: Postgres-9.4.Dockerfile
  ##    dockerfile: Postgres-9.5.Dockerfile
    # image: mdillon/postgis
    # environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    # ports:
      # - 15432:5432
    # volumes:
      # - postgres:/var/lib/postgresql/data
      # - ./pg_data:/var/lib/postgresql/data
  #  env_file:
  #    - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml

  #######################################
  # PostgreSQL server
  #######################################
  #postgres:
  #  build:
  #    context: ./webdevops_docker/docker/postgres/
  #    dockerfile: Postgres-9.4.Dockerfile
  #    dockerfile: Postgres-9.5.Dockerfile
  #  ports:
  #    - 15432:5432
  #  volumes:
  #    - postgres:/var/lib/postgresql/data
  #  env_file:
  #    - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml

  #######################################
  # Solr server
  #######################################
  #solr:
  #  build:
  #    context: ./webdevops_docker/docker/solr/
  #  volumes:
  #    - solr:/opt/solr/server/solr/data
  #  env_file:
  #    - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml
  #  environment:
  #    - SOLR_STORAGE=/opt/solr/server/solr/data
  #    - VIRTUAL_HOST=solr.boilerplate.docker
  #    - VIRTUAL_PORT=8983

  #######################################
  # Tika server
  #######################################
  #tika:
  #  build:
  #    context: ./webdevops_docker/docker/tika/
  #  ports:
  #    - 19998:9998

  #######################################
  # Elasticsearch
  #######################################
  #elasticsearch:
  #  build:
  #    context: ./webdevops_docker/docker/elasticsearch/
  #  ports:
  #    - 19200:9200
  #    - 19300:9300
  #  volumes:
  #    - elasticsearch:/usr/share/elasticsearch/data
  #  env_file:
  #    - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml
  #  environment:
  #    - VIRTUAL_HOST=elasticsearch.boilerplate.docker
  #    - VIRTUAL_PORT=9200

  #######################################
  # Redis
  #######################################
  redis:
    build:
      context: ./webdevops_docker/docker/redis/
    volumes:
      - redis:/data
    ports:
      - 16379:6379
      #- 6379:6379
    env_file:
      - ./webdevops_docker/etc/environment.yml
      - ./webdevops_docker/etc/environment.development.yml

  #######################################
  # Memcached
  #######################################
  #memcached:
  #  build:
  #    context: ./webdevops_docker/docker/memcached/
  #  env_file:
  #    - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml

  #######################################
  # Mail
  #######################################
  # Mailhog
  # mail:
    #  image: mailhog/mailhog
   #  ports:
   #    - 8025:8025
    #  environment:
    #   - VIRTUAL_HOST=mail.boilerplate.docker
    #   - VIRTUAL_PORT=8025

  # Mailcatcher
  #mail:
  #  image: schickling/mailcatcher
  #  environment:
  #    - VIRTUAL_HOST=mail.boilerplate.docker
  #    - VIRTUAL_PORT=1080


  # Mailsandbox
  #mail:
  #  image: webdevops/mail-sandbox
  #  environment:
  #    - VIRTUAL_HOST=mail.boilerplate.docker
  #    - VIRTUAL_PORT=80

  #######################################
  # FTP (vsftpd)
  #######################################
  #ftp:
  #  build:
  #    context: ./webdevops_docker/docker/vsftpd/
  #  volumes:
  #    - ./:/application/
  #  env_file:
  #    - ./webdevops_docker/etc/environment.yml
  #    - ./webdevops_docker/etc/environment.development.yml

  #######################################
  # phpMyAdmin
  #######################################
  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  links:
  #    - mysql
  #  environment:
  #    - PMA_HOSTS=mysql
  #    - VIRTUAL_HOST=pma.boilerplate.docker
  #    - VIRTUAL_PORT=80
  #  volumes:
  #    - phpmyadmin:/sessions

volumes:
#   mysql:
#   postgres:
#   postgresgis:
#   config-omnidb:
#   solr:
#   elasticsearch:
  redis:
#   phpmyadmin:
