version: '3'
services:
    web:
        image: nginx:stable
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /:/host_root
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - /:/host_root
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db:
        image: postgres:10.1
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - /:/host_root
    omnidb:
        image: taivokasper/omnidb
        volumes:
            # - config-omnidb:/etc/omnidb 
            - ./.docker/config-omnidblocal/omnidb/:/etc/omnidb/ 
            - /:/host_root
        # links:
        #     - db:db
        ports:
            - "8090:8080"
            - "25482:25482"
    
# volumes:
#   config-omnidb:
